---
################################################## SSH Key Configuration
core_user_ssh_authorized_keys:
- "{{ lookup('file', '~/.ssh/MasterKemoKey.pub-ah') }}"

core_user_ssh_private_key_path: '~/.ssh/MasterKemoKey'

cluster_name: k8s
cluster_domain: kemo.labs
fcos_stream: stable

fcos_bin_dir: /var/bin
crictl_version: "v1.23.0"
cni_version: "v1.0.1"
k8s_version: "1.22"
service_release_version: "v0.12.0"
          
# cluster_load_balancer_ip: an IP or "auto"
cluster_load_balancer_ip: 192.168.42.35

################################################## Cluster Node IPAM
# cluster_node_network_ipam: dhcp or static
cluster_node_network_ipam: static
######################### If cluster_node_network_ipam == static:
cluster_node_network_static_dns_servers:
  - 192.168.42.9
  - 192.168.42.10
cluster_node_network_static_dns_search_domains:
  - kemo.labs

cluster_nodes:
  - name: fcos-k8s-cp-1
    type: controlPlane
    vm:
      cpu_cores: 4
      cpu_sockets: 1
      cpu_threads: 1
      memory: 16384
      disks:
        - size: 60
          name: boot
    network:
      ip_address: 192.168.42.31
      cidr_prefix: 24
      gateway: 192.168.42.1

  - name: fcos-k8s-app-1
    type: applicationNode
    vm:
      cpu_cores: 6
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
      disks:
        - size: 130
          name: boot
    network:
      ip_address: 192.168.42.32
      cidr_prefix: 24
      gateway: 192.168.42.1

  - name: fcos-k8s-app-2
    type: applicationNode
    vm:
      cpu_cores: 6
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
      disks:
        - size: 130
          name: boot
    network:
      ip_address: 192.168.42.33
      cidr_prefix: 24
      gateway: 192.168.42.1

  - name: fcos-k8s-app-3
    type: applicationNode
    vm:
      cpu_cores: 6
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
      disks:
        - size: 130
          name: boot
    network:
      ip_address: 192.168.42.34
      cidr_prefix: 24
      gateway: 192.168.42.1

local_ansible_user: kemo

generated_asset_directory: ./.generated

libvirt_base_vm_path: /var/lib/libvirt/images

libvirt_host_bridge_iface: containerLANbr0
libvirt_like_options: "--network bridge={{ libvirt_host_bridge_iface }},model=virtio -v --memballoon none --cpu host-passthrough --autostart --noautoconsole --virt-type kvm --features kvm_hidden=on --controller type=scsi,model=virtio-scsi --graphics vnc,listen=0.0.0.0,tlsport=-1,defaultMode='insecure'"