---
- name: "Delete the VM disks for K8s Node - {{ node.name }}"
  file:
    state: absent
    path: "{{ libvirt_base_vm_path }}/{{ node.name }}-{{ disk.name }}.qcow2"
  loop: "{{ node.vm.disks }}"
  loop_control:
    loop_var: disk
    label: "{{ node.name }} @ {{ libvirt_base_vm_path }}/{{ node.name }}-{{ disk.name }}.qcow2"

- name: "Delete the VM disks for K8s Node - {{ node.name }}"
  file:
    state: absent
    path: "{{ libvirt_base_vm_path }}/{{ node.name }}.qcow2"
  loop: "{{ node.vm.disks }}"
  loop_control:
    loop_var: disk
    label: "{{ node.name }} @ {{ libvirt_base_vm_path }}/{{ node.name }}.qcow2"